[package]
name = "procon22_image"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
image = "0.24.3"
rutie = "0.8.4"

[lib]
name = "pro22kadai_image"
crate-type = ["cdylib"]
